{% set name = "teloscope" %}
{% set version = "0.0.1" %}
package:
  name: {{ name }}
  version: {{ version }}
source:
  url: https://github.com/vgl-hub/teloscope/releases/download/v{{version}}/teloscope.v{{version}}-with_submodules.zip
  sha256: 1c71a23070708f156d4c85bcf0c393f2e515f81f90cc0e1946963f5403e00d66
build:
  number: 0
  run_exports:
    - {{ pin_subpackage('teloscope', max_pin="x") }}
requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - zlib
test:
  commands:
    - teloscope -h | grep "teloscope"
about:
  home: https://github.com/vgl-hub/teloscope
  license_familiy: MIT
  license: MIT
  summary: A telomere annotation tools for genome assemblies
extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - biotools:teloscope
    - usegalaxy-eu:teloscope
  container:
    # extended-base generates en_US.UTF-8 locale and sets LC_ALL, LANG properly
    extended-base: true
  skip-lints:
    - uses_vcs_url
    - missing_hash
